# Generated by Django 4.1 on 2023-05-22 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ComparativeCondition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_what",
                    models.CharField(
                        choices=[
                            ("CA", "Chiffre d'affaires"),
                            ("MEA", "Mise en avant"),
                            ("gondole", "Tête de gondole"),
                        ],
                        default="CA",
                        max_length=100,
                        verbose_name="Quoi 1",
                    ),
                ),
                (
                    "first_start_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date de début 1"
                    ),
                ),
                (
                    "first_end_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date de fin 1"
                    ),
                ),
                (
                    "operator",
                    models.CharField(
                        blank=True,
                        choices=[("lt", "<"), ("gt", ">"), ("eq", "=")],
                        max_length=100,
                        null=True,
                        verbose_name="Opérateur",
                    ),
                ),
                (
                    "quantity",
                    models.FloatField(blank=True, null=True, verbose_name="Quantité"),
                ),
                (
                    "second_what",
                    models.CharField(
                        choices=[
                            ("CA", "Chiffre d'affaires"),
                            ("MEA", "Mise en avant"),
                            ("gondole", "Tête de gondole"),
                        ],
                        default="CA",
                        max_length=100,
                        verbose_name="Quoi 2",
                    ),
                ),
                (
                    "second_start_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date de début 2"
                    ),
                ),
                (
                    "second_end_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date de fin 2"
                    ),
                ),
                (
                    "rate_reduction",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Taux de remise"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NoCondition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rate_reduction",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Taux de remise"
                    ),
                ),
                (
                    "who",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("produit", "Produit"),
                            ("gamme", "Gamme"),
                            ("total", "Total"),
                        ],
                        max_length=100,
                        null=True,
                        verbose_name="Qui",
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date de début 1"
                    ),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date de fin 2"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Pharmacy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("group", models.CharField(max_length=100, null=True)),
                ("labo_name", models.CharField(max_length=100, null=True)),
                ("type", models.CharField(max_length=100, null=True)),
                ("subtype", models.CharField(max_length=100, null=True)),
                ("ca", models.IntegerField(null=True)),
                ("start_date", models.DateTimeField(null=True)),
                ("end_date", models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="SimpleCondition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "what",
                    models.CharField(
                        choices=[
                            ("CA", "Chiffre d'affaires"),
                            ("MEA", "Mise en avant"),
                            ("gondole", "Tête de gondole"),
                        ],
                        default="CA",
                        max_length=100,
                        verbose_name="Quoi",
                    ),
                ),
                (
                    "who",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("produit", "Produit"),
                            ("gamme", "Gamme"),
                            ("total", "Total"),
                        ],
                        max_length=100,
                        null=True,
                        verbose_name="Qui",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        blank=True,
                        choices=[("T1", "TYPE_1"), ("T2", "TYPE_2"), ("T3", "TYPE_3")],
                        max_length=100,
                        null=True,
                        verbose_name="Type",
                    ),
                ),
                (
                    "operator",
                    models.CharField(
                        blank=True,
                        choices=[("lt", "<"), ("gt", ">"), ("eq", "=")],
                        max_length=100,
                        null=True,
                        verbose_name="Opérateur",
                    ),
                ),
                (
                    "quantity",
                    models.FloatField(blank=True, null=True, verbose_name="Quantité"),
                ),
                (
                    "unit",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("currency", "€"),
                            ("percentile", "%"),
                            ("quantity", "quantité"),
                        ],
                        max_length=100,
                        null=True,
                        verbose_name="Unité",
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date de début"
                    ),
                ),
                (
                    "end_date",
                    models.DateField(blank=True, null=True, verbose_name="Date de fin"),
                ),
                (
                    "rate_reduction",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Taux de remise"
                    ),
                ),
            ],
        ),
    ]
