# Generated by Django 4.1 on 2023-05-23 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newapp", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="pharmacy", old_name="name", new_name="pharma_name",
        ),
        migrations.AddField(
            model_name="pharmacy",
            name="ca_evolution",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="pharmacy",
            name="cip",
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="pharmacy",
            name="product",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="pharmacy", name="unit", field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="pharmacy",
            name="unit_evolution",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="pharmacy", name="year", field=models.IntegerField(null=True),
        ),
    ]
