# Generated by Django 4.1 on 2023-05-23 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newapp", "0002_rename_name_pharmacy_pharma_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pharmacy", name="cip", field=models.IntegerField(),
        ),
    ]
